// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppPageHeading: typeof import('./src/components/AppPageHeading.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardDragAndDrop: typeof import('./src/components/BoardDragAndDrop.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconDropZone: typeof import('./src/components/icons/IconDropZone.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconProfile: typeof import('./src/components/icons/IconProfile.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconUserGroup: typeof import('./src/components/icons/IconUserGroup.vue')['default']
    IconWarning: typeof import('./src/components/icons/IconWarning.vue')['default']
    InputFile: typeof import('./src/components/InputFile.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TailModal: typeof import('./src/components/TailModal.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TheAlerts: typeof import('./src/components/TheAlerts.vue')['default']
    TheDrawer: typeof import('./src/components/TheDrawer.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TrBoard: typeof import('./src/components/TrBoard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

export {}
